/**
 * 安全事件类型（与 SAFE_DESIGN 一致）
 */
export const SecurityEventType = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT: 'LOGOUT',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  UNAUTHORIZED_ACCESS: 'UNAUTHORIZED_ACCESS',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  SUSPICIOUS_ACTIVITY: 'SUSPICIOUS_ACTIVITY',
  SECURE_CHANNEL_INIT: 'SECURE_CHANNEL_INIT',
  SECURE_REPLAY_BLOCKED: 'SECURE_REPLAY_BLOCKED',
  SECURE_SIGNATURE_INVALID: 'SECURE_SIGNATURE_INVALID',
  SECURE_DECRYPT_FAILED: 'SECURE_DECRYPT_FAILED',
} as const;

export type SecurityEventType = (typeof SecurityEventType)[keyof typeof SecurityEventType];

export const SecuritySeverity = {
  LOW: 'low',
  MEDIUM: 'medium',
  HIGH: 'high',
  CRITICAL: 'critical',
} as const;
